apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/your-org/fast-and-furious-deploy.git'
    targetRevision: main
    path: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true