apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fast-and-furious
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vdyshlevyi/fast-and-furious-deploy.git'
    targetRevision: HEAD
    path: charts/fast-and-furious
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
